services:
  streamlit-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile  # Explicit relative path
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
