# rag_pdf_streamlit/.streamlit/config.toml
[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableStaticServing = false
runOnSave = true
maxUploadSize = 50

[browser]
gatherUsageStats = true